// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Word struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Forms                []string   `protobuf:"bytes,2,rep,name=forms,proto3" json:"forms,omitempty"`
	Contents             []*Content `protobuf:"bytes,3,rep,name=contents,proto3" json:"contents,omitempty"`
	ShowExample          bool       `protobuf:"varint,4,opt,name=showExample,proto3" json:"showExample,omitempty"`
	ExampleSentences     []string   `protobuf:"bytes,5,rep,name=exampleSentences,proto3" json:"exampleSentences,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Word) GetForms() []string {
	if m != nil {
		return m.Forms
	}
	return nil
}

func (m *Word) GetContents() []*Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Word) GetShowExample() bool {
	if m != nil {
		return m.ShowExample
	}
	return false
}

func (m *Word) GetExampleSentences() []string {
	if m != nil {
		return m.ExampleSentences
	}
	return nil
}

type Slice struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Imported             bool     `protobuf:"varint,2,opt,name=imported,proto3" json:"imported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slice) Reset()         { *m = Slice{} }
func (m *Slice) String() string { return proto.CompactTextString(m) }
func (*Slice) ProtoMessage()    {}
func (*Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slice.Unmarshal(m, b)
}
func (m *Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slice.Marshal(b, m, deterministic)
}
func (m *Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slice.Merge(m, src)
}
func (m *Slice) XXX_Size() int {
	return xxx_messageInfo_Slice.Size(m)
}
func (m *Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Slice proto.InternalMessageInfo

func (m *Slice) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Slice) GetImported() bool {
	if m != nil {
		return m.Imported
	}
	return false
}

type Content struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Explain              []*Slice `protobuf:"bytes,2,rep,name=explain,proto3" json:"explain,omitempty"`
	ExampleSentences     []string `protobuf:"bytes,3,rep,name=exampleSentences,proto3" json:"exampleSentences,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Content) GetExplain() []*Slice {
	if m != nil {
		return m.Explain
	}
	return nil
}

func (m *Content) GetExampleSentences() []string {
	if m != nil {
		return m.ExampleSentences
	}
	return nil
}

func init() {
	proto.RegisterType((*Word)(nil), "entity.Word")
	proto.RegisterType((*Slice)(nil), "entity.slice")
	proto.RegisterType((*Content)(nil), "entity.Content")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xa5, 0xdb, 0x76, 0xdb, 0x9d, 0x2a, 0xca, 0xe0, 0x21, 0x78, 0x0a, 0xbd, 0x58, 0x14, 0xf6,
	0xb0, 0x9e, 0x3d, 0x89, 0x3f, 0x10, 0x0f, 0x9e, 0x6b, 0x77, 0xc4, 0x42, 0x9b, 0x84, 0x24, 0xe0,
	0xee, 0x37, 0xf9, 0x93, 0xd2, 0x24, 0x2d, 0xc2, 0xf6, 0xf6, 0xde, 0x4b, 0x66, 0xde, 0x7b, 0x03,
	0x57, 0x24, 0x5d, 0xef, 0xce, 0x7b, 0x6d, 0x94, 0x53, 0xb8, 0x0d, 0xac, 0xfe, 0x4d, 0x20, 0xfb,
	0x50, 0xe6, 0x88, 0x08, 0x99, 0x6c, 0x47, 0x62, 0x09, 0x4f, 0x9a, 0x9d, 0xf0, 0x18, 0xef, 0x20,
	0xff, 0x52, 0x66, 0xb4, 0x6c, 0xc3, 0xd3, 0x66, 0x27, 0x02, 0xc1, 0x27, 0x28, 0x3b, 0x25, 0x1d,
	0x49, 0x67, 0x59, 0xca, 0xd3, 0xa6, 0x3a, 0xdc, 0xec, 0xe3, 0xee, 0xd7, 0xa0, 0x8b, 0xe5, 0x03,
	0x72, 0xa8, 0xec, 0xb7, 0xfa, 0x79, 0x3b, 0xb5, 0xa3, 0x1e, 0x88, 0x65, 0x3c, 0x69, 0x4a, 0xf1,
	0x5f, 0xc2, 0x47, 0xb8, 0xa5, 0x00, 0xdf, 0x69, 0x1a, 0xea, 0xc8, 0xb2, 0xdc, 0xfb, 0x5d, 0xe8,
	0xf5, 0x0b, 0xe4, 0x76, 0xe8, 0x3b, 0x42, 0x06, 0x45, 0xb4, 0x88, 0x81, 0x67, 0x8a, 0xf7, 0x50,
	0xf6, 0xa3, 0x56, 0xc6, 0xd1, 0x91, 0x6d, 0xbc, 0xdb, 0xc2, 0x6b, 0x03, 0x45, 0x4c, 0x38, 0xd5,
	0x75, 0x67, 0xbd, 0xd4, 0x9d, 0x30, 0x3e, 0x40, 0x41, 0x27, 0x3d, 0xb4, 0xbd, 0xf4, 0x85, 0xab,
	0xc3, 0xf5, 0xdc, 0xcb, 0x9b, 0x8a, 0xf9, 0x75, 0x35, 0x72, 0xba, 0x1e, 0xf9, 0x73, 0xeb, 0xef,
	0xfd, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x19, 0xf5, 0x72, 0x7f, 0x01, 0x00, 0x00,
}
